### ISSUE TITLE
router performance observation

### ISSUE THREAD

**Issue by 404pnf** [manastech/frank#4]
When number of routes increase, router performance drops linearly (still amazing, though : ).
## Generate routes.

``` ruby
# ruby
s = (1..1000).to_a.map { |e| %Q(get "/#{e}" { "hello" } ) }.join("\n")
File.write('frank_router_performance.cr', s)

```
## Test performace

``` bash

 wrk -c100 -t 2 -d 10s http://127.0.0.1:3000/1
 wrk -c100 -t 2 -d 10s http://127.0.0.1:3000/100
 wrk -c100 -t 2 -d 10s http://127.0.0.1:3000/500
 wrk -c100 -t 2 -d 10s http://127.0.0.1:3000/1000

```

Linear drop of performance.  Because of @routes = [] of Route ?

I don't think it's an issue in production, most app only have several  routes.

**Comment by matiasgarciaisaia** [comment]
Thanks for the report. We're archiving the repo.
